### ISSUE TITLE
Keep previous bio in textarea when you edit the bio

### ISSUE THREAD

**Issue by zac-garby** [j4cobgarby/Cordial#14]

**Comment by j4cobgarby** [comment]
This works now, although as a brand new user, the default bio ("This user hasn't set a bio", etc..) shows up.
The problem with fixing this is that there's no value saying whether or not they've changed it, and instead there's just a default value, but since I've changed this value, not every user has the same default bio

**Comment by zac-garby** [comment]
You could leave the bio empty by default, and then when you display it, say "This user hasn't set a bio" if it's empty.

**Comment by j4cobgarby** [comment]
I could, I suppose

**Comment by j4cobgarby** [comment]
Okay, I've fixed this now.
